[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read-write", path = "log/"}, { access = "read", path = "env"}]
dotenv = true
solc_version = "0.8.27"
evm_version = "cancun"
# Fast compilation settings for development
viaIR = true
optimizer = false

# NOTE: the default profile will be used for dev compilation and testing

# Production profile - full optimization
[profile.production]
viaIR = true
optimizer = true
optimizer_runs = 10000

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
unichain = "${UNICHAIN_MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
unichain = { key = "${UNICHAIN_API_KEY}", url = "https://unichain.blockscout.com/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
