[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read-write", path = "log/"}]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true
optimizer = true
optimizer_runs = 100_000
dotenv = true  # Enable .env file loading
exclude_paths = ["test/old-tests"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/",
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/v4-core/lib/openzeppelin-contracts/",
    "uniswap-hooks/=lib/uniswap-hooks/src/"
]

# Sepolia configuration for integration testing
[profile.sepolia]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true
# Sepolia settings
eth_rpc_url = "${SEPOLIA_RPC_URL}"
chain_id = 11155111

# Unichain Sepolia configuration for E2E testing
[profile.unichain-sepolia]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true
dotenv = true
# Unichain Sepolia settings
eth_rpc_url = "${UNICHAIN_SEPOLIA_RPC_URL}"
chain_id = 1301

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fuzz]
runs = 256 # Default fuzz runs

[fuzz.overrides."src/libraries/MathUtils.sol:MathUtils.testComputeLiquidityFromAmounts(uint160,uint160,uint160,uint256,uint256)"]
# Constrain amount0 and amount1 to prevent hitting known V4 core overflow reverts
# Using approximately type(uint128).max * 10 as a large but reasonable limit
max_inputs = { amount0 = "3402823669209384634633746074317682114550", amount1 = "3402823669209384634633746074317682114550" }