[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read-write", path = "log/"}, { access = "read", path = "env"}]
dotenv = true  # Enable .env file loading
solc_version = "0.8.27"
evm_version = "cancun"
viaIR = true
optimizer = true
optimizer_runs = 1 # TODO: use 10000

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
