name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      # Node + pnpm setup
      - name: Set up Node 20 LTS and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: corepack enable

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Install JS/TS deps (Solmate, OZ, Uniswap, etc.)
      - name: Install pnpm dependencies
        run: pnpm install --frozen-lockfile

      # Audit dependencies
      - name: Audit dependencies
        run: pnpm audit

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      # Compare snapshots
      - name: Compare snapshots
        run: |
          forge snapshot
          forge snapshot --check

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
